webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/public/build'

    # Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: true

    # If using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    # crossorigin: 'anonymous'

    # Preload all rendered script and link tags automatically via the HTTP/2 Link header
    preload: true


framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
